pipeline {
    agent any 
    stages {
        stage('Excute test package') {
            steps {
                //Start ET
                startET toolName:'ECU-TEST',workspaceDir:'C:\\0_ET_Workspace\\Git\\ECU-TEST\\TestWorkspace'
                
                //Run package
                testPackage testConfig: [constants: [], forceReload: false, keepConfig: false, loadOnly: false,tbcFile:'C:\\0_ET_Workspace\\Git\\ECU-TEST\\TestWorkspace\\Configurations\\Testlab_HiL.tbc',tcfFile:'C:\\0_ET_Workspace\\Git\\ECU-TEST\\TestWorkspace\\Configurations\\SW_Ver_1.tcf'],testFile:'C:\\0_ET_Workspace\\Git\ECU-TEST\\TestWorkspace\\Packages\\_Results\\50_TestCaseDevelopment\\BasicDrive.pkg'
                
      
            }
        }
    }
}